<a href="https://colab.research.google.com/github/JBadawood/Kaggle/blob/main/Intro_to_ML-Kaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a name='intro'></a>
# **Introduction to Machine Learning** 
*Learn the core ideas in machine learning, and build your first models.*\
https://www.kaggle.com/learn/intro-to-machine-learning

**تعلم الآلة**\
*مجال فرعي للذكاء الاصطناعي **يهتم بتعلم الأنماط** من البيانات المتاحة لعمل **تنبؤات** أو **قرارات** مبنية على بيانات جديدة دون برمجة صريحة*

**Machine Learning (ML)**\
*An AI subfield concerned with **learning patterns** from available data to make **predictions** or **decisions** based on new data without explicit programming.*

>المصدر: [معجـــم البيانـــات والـــذكاء االصطناعـــي](https://sdaia.gov.sa/files/Dictionary.pdf) من الهيئة السعودية للبيانات والذكاء الاصطناعي بالتعاون مع مجمع الملك سلمان العالمي للغة العربية (الطبعة الأولى 2022)

____

**Kaggle**
> **Step1:** [Intro to Programming](https://www.kaggle.com/learn/intro-to-programming) (💯 DONE 🙂) \
**Step2:** [Python](https://www.kaggle.com/learn/python) (💯 DONE 🙂)\
**Step3:** [Intro to Machine Learning](https://www.kaggle.com/learn/intro-to-machine-learning) (NOW 💪)

> **[TensorFlow Guide](https://www.kaggle.com/learn-guide/tensorflow)**\
**Step4:** [Intro to Deep Learning](https://www.kaggle.com/learn/intro-to-deep-learning)\
**Step5:** [Computer Vision](https://www.kaggle.com/learn/computer-vision)

>**Step6:** [Pandas](https://www.kaggle.com/learn/pandas)\
**Step7:** [Intermediate Machine Learning](https://www.kaggle.com/learn/intermediate-machine-learning)\
**Step8:** [Feature Engineering](https://www.kaggle.com/learn/feature-engineering)\
**Step9:** [Time Series](https://www.kaggle.com/learn/time-series)

----
**Coursera | ML & DL**
>**Step10:** [Machine Learning Specialization](https://www.deeplearning.ai/program/machine-learning-specialization/) (DeepLearning.AI & Stanford)\
**Step11:** [The Deep Learning Specialization](https://www.deeplearning.ai/program/deep-learning-specialization/) (DeepLearning.AI & Stanford)

||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

**Additional Resources**\
**Microsoft | AI for Beginners**
>- [Artificial Intelligence for Beginners](https://github.com/microsoft/ai-for-beginners)
>- [Classic Machine Learning for Beginners](https://github.com/microsoft/ML-For-Beginners)
>- [Data Science for Beginners](https://github.com/microsoft/Data-Science-For-Beginners)

==============================================================

**IBM & UDACITY | Data Science & Analysis**
> **Course1:** [Python for Data Science](https://cognitiveclass.ai/courses/python-for-data-science) == [AI Programming with Python](https://www.udacity.com/course/ai-programming-python-nanodegree--nd089)
\
**Course2:** [Data Analysis with Python](https://cognitiveclass.ai/courses/data-analysis-python)\
**Course3:** [Machine Learning with Python](https://cognitiveclass.ai/courses/machine-learning-with-python) or 
[Intro to Machine Learning with TensorFlow](https://www.udacity.com/course/intro-to-machine-learning-with-tensorflow-nanodegree--nd230)

# **Table of Contents**
[Intro. and Plan of Learning](#intro)

1. [How Models Work](#ch1)

2. [Basic Data Exploration](#ch2)\
  2.1 [Using Pandas to Get Familiar With Your Data](#sec2-1)\
  2.2 [Interpreting Data Description](#sec2-2)\
  [Exercise: Explore Your Data](#ex1)

3. [Your First Machine Learning Model](#ch3)

4. [Model Validation](#ch4)

5. [Underfitting and Overfitting](#ch5)

6. [Random Forests](#ch6)

7. [Machine Learning Competitions](#ch7)

[Bonus Exercise : Titanic Tutorial](#bonus)

**Install Kaggle exercises in Google Colab** ([link of steps](https://www.kaggle.com/questions-and-answers/165757))\
https://github.com/Kaggle/learntools

```
!git clone https://github.com/Kaggle/learntools.git
!mv learntools learntools_dir
!mv learntools_dir/learntools learntools
```

<a name='ch1'></a>
## **1- How Models Work**
The first step if you're new to machine learning.\
https://www.kaggle.com/code/dansbecker/how-models-work

قبل بناء أي نموذج نحتاج بيانات سابقة تم جمعها. مثلًا:

لو نبغى نتوقع أسعار البيوت الجديدة راح يتطلب مننا قبلها أننا نعرف كم كانت أسعار البيوت القديمة وكذلك الموجودة حاليًا (يعني نشوف الـ history)

بهذه الطريقة راح نعرف الـ patterns لهذه الأسعار السابقة ومن ثم يمكننا الاستفادة منها لعمل predictions للبيوت الجديدة

We'll start with a model called the **Decision Tree**. There are fancier models that give more accurate predictions. But decision trees are easy to understand, and they are *the basic building block for some of the best models* in **data science**.

> You can capture more factors using a tree that has more "**splits**." The most factors affecting home price, are: 
- number of bathrooms, 
- lot size, 
- location, etc.

> These are called **"deeper" trees**. The predicted price for the house is *at the bottom of the tree*. The point at the bottom where we make a prediction is called a **leaf**.

We use data to decide how to break the houses into two groups, and then again to determine the predicted price in each group. This step of capturing patterns from data is called **fitting** or **training** the model. The data used to **fit** the model is called the **training data**.

After the model has been fit, you can apply it to new data to **predict** prices of additional homes.

<a name='ch2'></a>
## **2- Basic Data Exploration**
Load and understand your data.\
https://www.kaggle.com/code/dansbecker/basic-data-exploration

<a name='sec2-1'></a>
### 2-1 Using Pandas to Get Familiar With Your Data
https://www.kaggle.com/code/dansbecker/basic-data-exploration?scriptVersionId=79125477&cellId=1

أول خطوة نحتاجها هي أننا نفهم البيانات اللي عندنا 

عشان كذا نحتاج pandas كوحدة من الأدوات اللي راح تساعدنا على استكشاف ومعالجة البيانات

In [1]:
import pandas as pd

#### Melbourne Housing Snapshot
https://www.kaggle.com/datasets/dansbecker/melbourne-housing-snapshot

We'll look at data about home prices in Melbourne, Australia.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# راح يتم قراءة الملف وتخزينه في DataFrame
melbourne_data = pd.read_csv('/content/drive/MyDrive/iMLND/Kaggle/Intro_to_ML/melb_data.csv')

In [4]:
# نقدر نشوف أول خمسة صفوف من هذا الملف
melbourne_data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [5]:
# هذا الكود عشان نشوف ملخص عن البيانات اللي عندنا
melbourne_data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,13580.000000,1.358000e+04,13580.000000,13580.000000,13580.000000,13580.000000,13518.000000,13580.000000,7130.000000,8205.000000,13580.000000,13580.000000,13580.000000
mean,2.937997,1.075684e+06,10.137776,3105.301915,2.914728,1.534242,1.610075,558.416127,151.967650,1964.684217,-37.809203,144.995216,7454.417378
std,0.955748,6.393107e+05,5.868725,90.676964,0.965921,0.691712,0.962634,3990.669241,541.014538,37.273762,0.079260,0.103916,4378.581772
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1196.000000,-38.182550,144.431810,249.000000
25%,2.000000,6.500000e+05,6.100000,3044.000000,2.000000,1.000000,1.000000,177.000000,93.000000,1940.000000,-37.856822,144.929600,4380.000000
50%,3.000000,9.030000e+05,9.200000,3084.000000,3.000000,1.000000,2.000000,440.000000,126.000000,1970.000000,-37.802355,145.000100,6555.000000
75%,3.000000,1.330000e+06,13.000000,3148.000000,3.000000,2.000000,2.000000,651.000000,174.000000,1999.000000,-37.756400,145.058305,10331.000000
max,10.000000,9.000000e+06,48.100000,3977.000000,20.000000,8.000000,10.000000,433014.000000,44515.000000,2018.000000,-37.408530,145.526350,21650.000000

<a name='sec2-2'></a>
### 2-2 Interpreting Data Description
https://www.kaggle.com/code/dansbecker/basic-data-exploration?scriptVersionId=79125477&cellId=5

من ملخص البيانات السابق نقدر نعرف كل من:
- عدد الصفوف اللي ما فيها missing values (count)
- متوسط القيم حق العمود mean
- الإنحراف المعياري (عشان نعرف انتشار البيانات) (standard deviation)
- القيمة الصغرى min
- الربيعات Interquartile
> 1- الربيع الأدنى Q1(25%)\
2- الوسيط Q2(50%)\
3- الربيع الأعلى Q3(75%)
- القيمة العظمى max

<a name='ex1'></a>
### Exercise: Explore Your Data

<a name='ch3'></a>
## **3- Your First Machine Learning Model**
Building your first model.\
https://www.kaggle.com/code/dansbecker/your-first-machine-learning-model

<a name='ch4'></a>
## **4- Model Validation**
Measure the performance of your model, so you can test and compare alternatives.\
https://www.kaggle.com/code/dansbecker/model-validation

<a name='ch5'></a>
## **5- Underfitting and Overfitting**
Fine-tune your model for better performance.\
https://www.kaggle.com/code/dansbecker/underfitting-and-overfitting

<a name='ch6'></a>
## **6- Random Forests**
Using a more sophisticated machine learning algorithm.\
https://www.kaggle.com/code/dansbecker/random-forests

<a name='ch7'></a>
## **7- Machine Learning Competitions**
Enter the world of machine learning competitions to keep improving and see your progress.\
https://www.kaggle.com/code/alexisbcook/machine-learning-competitions

<a name='bonus'></a>
## **Bonus Exercise : Titanic Tutorial**

Make your first submission to a Kaggle competition!

\
The [notebook](https://www.kaggle.com/code/alexisbcook/titanic-tutorial/notebook) is beginner-friendly and does not assume you have any experience with coding. At the same time, you'll learn how to author your own notebooks on Kaggle, and *it gives you a great idea of what you'll be able to do* if you continue to learn **data science**!

\
If you're interested in learning more, we strongly suggest our (3-hour) [Intro to Machine Learning course](https://www.kaggle.com/learn/intro-to-machine-learning), which will help you fully understand all of the code that we've presented here. You'll also know enough to generate even better predictions!

In this section,**you'll train your own machine learning model to improve your predictions**. If you've never written code before or don't have any experience with **machine learning**, don't worry! We don't assume any prior experience in this tutorial.

### Load the data

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/content/drive/MyDrive/iMLND/Titanic'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/content/drive/MyDrive/iMLND/Titanic/titanic.zip
/content/drive/MyDrive/iMLND/Titanic/gender_submission.csv
/content/drive/MyDrive/iMLND/Titanic/train.csv
/content/drive/MyDrive/iMLND/Titanic/test.csv

In [ ]:
train_data = pd.read_csv('/content/drive/MyDrive/iMLND/Titanic/train.csv')
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
test_data = pd.read_csv('/content/drive/MyDrive/iMLND/Titanic/test.csv')
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

- Find **patterns** in train.csv that help us **predict** whether the passengers in test.csv survived

### Explore a pattern

The sample submission file in **gender_submission.csv** assumes that all female passengers survived (and all male passengers died).

Is this a reasonable first guess? We'll check if this pattern holds true in the data (in **train.csv**).

In [ ]:
women = train_data.loc[train_data.Sex == 'female']['Survived']
rate_women = sum(women)/len(women)

print("% of women who survived:", rate_women)

% of women who survived: 0.7420382165605095

In [ ]:
men = train_data.loc[train_data.Sex == 'male']['Survived']
rate_men = sum(men)/len(men)

print("% of men who survived:", rate_men)

% of men who survived: 0.18890814558058924

> From this you can see that almost 75% of the women on board survived, whereas only 19% of the men lived to tell about it. Since gender seems to be such a strong indicator of survival, the submission file in **gender_submission.csv** is not a bad first guess!

This gender-based submission bases its predictions **on only a single column**. As you can imagine, by **considering multiple columns**, we can discover more **complex patterns** that can potentially yield better-informed predictions.*Since it is quite difficult to consider several columns at once (or, it would take a long time to consider all possible patterns in many different columns simultaneously), we'll use **machine learning to automate this** for us.*

### Machine learning model

- Build a **random forest model**
 *the random forest model makes a democratic decision: the outcome with the **most votes wins**!*

The code cell below looks for patterns in four different columns ("**Pclass**", "**Sex**", "**SibSp**", and "**Parch**") of the data. It constructs the trees in the random forest model based on patterns in the **train.csv** file, before generating predictions for the passengers in **test.csv**. The code also saves these new predictions in a CSV file **submission.csv**.

In [ ]:
from sklearn.ensemble import RandomForestClassifier

y = train_data['Survived']

features = ["Pclass","Sex","SibSp","Parch"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X,y)
predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId':test_data.PassengerId,
                       'Survived': predictions})

output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!