<a href="https://colab.research.google.com/github/JBadawood/Kaggle/blob/main/Python-Kaggle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a name='intro'></a>
# **Python** 
*Learn the most important language for data science.*\
https://www.kaggle.com/learn/python

This course covers the key Python skills you’ll need so you can **start using Python for data science.**

> The newest **Intro to Programming course** (💯 DONE 🙂) is ***designed for people who have never written a single line of code. You’ll learn how to code in Python, from the very beginning.***

> After completing this course, you will then be ready for the **Python course** (NOW 💪), designed for people with some programming experience. Then you can apply your knowledge to the **Intro to Machine Learning course** and the **Intermediate Machine Learning course**.

____

**Kaggle**
> **Step1:** [Intro to Programming](https://www.kaggle.com/learn/intro-to-programming) (💯 DONE 🙂) \
**Step2:** [Python](https://www.kaggle.com/learn/python) (NOW 💪)\
**Step3:** [Intro to Machine Learning](https://www.kaggle.com/learn/intro-to-machine-learning)\
**Step4:** [Intro to Deep Learning](https://www.kaggle.com/learn/intro-to-deep-learning)\
**Step5:** [Computer Vision](https://www.kaggle.com/learn/computer-vision)

>**Step6:** [Pandas](https://www.kaggle.com/learn/pandas)\
**Step7:** [Intermediate Machine Learning](https://www.kaggle.com/learn/intermediate-machine-learning)\
**Step8:** [Feature Engineering](https://www.kaggle.com/learn/feature-engineering)\
**Step9:** [Time Series](https://www.kaggle.com/learn/time-series)

----
**Coursera | ML & DL**
>**Step10:** [Machine Learning Specialization](https://www.deeplearning.ai/program/machine-learning-specialization/) (DeepLearning.AI & Stanford)\
**Step11:** [The Deep Learning Specialization](https://www.deeplearning.ai/program/deep-learning-specialization/) (DeepLearning.AI & Stanford)

||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

**Additional Resources**\
**Microsoft | AI for Beginners**
>- [Artificial Intelligence for Beginners](https://github.com/microsoft/ai-for-beginners)
>- [Classic Machine Learning for Beginners](https://github.com/microsoft/ML-For-Beginners)
>- [Data Science for Beginners](https://github.com/microsoft/Data-Science-For-Beginners)

==============================================================

**IBM & UDACITY | Data Science & Analysis**
> **Course1:** [Python for Data Science](https://cognitiveclass.ai/courses/python-for-data-science) == [AI Programming with Python](https://www.udacity.com/course/ai-programming-python-nanodegree--nd089)
\
**Course2:** [Data Analysis with Python](https://cognitiveclass.ai/courses/data-analysis-python)\
**Course3:** [Machine Learning with Python](https://cognitiveclass.ai/courses/machine-learning-with-python) or 
[Intro to Machine Learning with TensorFlow](https://www.udacity.com/course/intro-to-machine-learning-with-tensorflow-nanodegree--nd230)

# **Table of Contents**
[Intro. and Plan of Learning](#intro)
1. [Hello, Python](#ch1)\
  1.1[Intro.](#sec1-1)\
  1.2 [Numbers and arithmetic in Python](#sec1-2)\
  [Exercise: Syntax, Variables, and Numbers](#ex1)
2. [Functions and Getting Help](#ch2)\
  2.1 [Getting Help](#sec2-1)\
  2.2 [Defining functions](#sec2-2)\
  2.3 [Functions that don't return](#sec2-3)\
  2.4 [Default arguments](#sec2-4)\
  2.5 [Functions Applied to Functions](#sec2-5)\
  [Exercise: Functions and Getting Help](#ex2)
3. [Booleans and Conditionals](#ch3)\
  3.1 [Booleans](#sec3-1)\
  3.2 [Conditionals](#sec3-2)\
  [Exercise: Booleans and Conditionals](#ex3)
4. [Lists](#ch4)
5. [Loops and List Comprehensions](#ch5)
6. [Strings and Dictionaries](#ch6)
7. [Working with External Libraries](#ch7)\
[Bonus Exercise : Titanic Tutorial](#bonus)

**Install Kaggle exercises in Google Colab** ([link of steps](https://www.kaggle.com/questions-and-answers/165757))\
https://github.com/Kaggle/learntools

```
!git clone https://github.com/Kaggle/learntools.git
!mv learntools learntools_dir
!mv learntools_dir/learntools learntools
```

<a name='ch1'></a>
## **1- Hello, Python**

<a name='sec1-1'></a>
### 1-1 Intro.
https://www.kaggle.com/code/colinmorris/hello-python#Hello,-Python!

In [ ]:
spam_amount = 0
print(spam_amount)

# Ordering Spam, egg, Spam, Spam, bacon and Spam (4 more servings of Spam)
spam_amount = spam_amount + 4

if spam_amount > 0:
    print("But I don't want ANY spam!")

viking_song = "Spam " * spam_amount
print(viking_song)

0
But I don't want ANY spam!
Spam Spam Spam Spam

#### Variable assignment

In [ ]:
spam_amount = 0 #Variable assignment

#### Function calls

In [ ]:
print(spam_amount) #Function calls

# function  is print()
# argumnets is spam_amount (the inputs)

0

<a name='sec1-2'></a>
### 1-2 Numbers and arithmetic in Python
https://www.kaggle.com/code/colinmorris/hello-python#Numbers-and-arithmetic-in-Python

In [ ]:
spam_amount = 0

In [ ]:
type(spam_amount)

int

In [ ]:
type(19.95)

float

In [ ]:
a = 4
b = 2
print('a + b =',a+b)
print('a - b =',a-b)
print('a * b =',a*b)
print('a / b =',a/b)

a + b = 6
a - b = 2
a * b = 8
a / b = 2.0

In [ ]:
a = 5
b = 2
print('a / b = {} is True division'.format(a/b))
print('a // b = {} is Floor division or rounded down (removing fractional parts)'.format(a//b))
print('a % b = {} is Modulus (Integer remainder after division)'.format(a%b))
print('a ** b = {} is Exponentiation'.format(a**b))
print('-a = {} is Negation'.format(-a))

a / b = 2.5 is True division
a // b = 2 is Floor division or rounded down (removing fractional parts)
a % b = 1 is Modulus (Integer remainder after division)
a ** b = 25 is Exponentiation
-a = -5 is Negation

#### Order of operations

**PEMDAS** - **P**arentheses, **E**xponents, **M**ultiplication/**D**ivision, **A**ddition/**S**ubtraction

In [ ]:
8 - 3 + 2

7

In [ ]:
-3 + 4 * 2

5

In [ ]:
hat_height_cm = 25
my_height_cm = 190
# How tall am I, in meters, when wearing my hat?
total_height_meters = hat_height_cm + my_height_cm / 100
print("Height in meters =", total_height_meters, "?")

Height in meters = 26.9 ?

Parentheses are useful here. You can add them to force Python to evaluate sub-expressions in whatever order you want.

In [ ]:
total_height_meters = (hat_height_cm + my_height_cm) / 100
print("Height in meters =", total_height_meters)

Height in meters = 2.15

#### Builtin functions for working with numbers

In [ ]:
print(min(1, 2, 3))
print(max(1, 2, 3))

1
3

In [ ]:
# The absolute value of an argument
print(abs(32))
print(abs(-32))

32
32

In [ ]:
print(float(10))
print(int(3.33))

print(int('807') + 1)

10.0
3
808

<a name='ex1'></a>
### Exercise: Syntax, Variables, and Numbers

#### Question 1

In [ ]:
# Create a variable called color
color = "Yellow"

#### Question 2

<hr/>
The table of available arithmetic operations:



| Operator     | Name           | Description                                            |
|--------------|----------------|--------------------------------------------------------|
| ``a + b``    | Addition       | Sum of ``a`` and ``b``                                 |
| ``a - b``    | Subtraction    | Difference of ``a`` and ``b``                          |
| ``a * b``    | Multiplication | Product of ``a`` and ``b``                             |
| ``a / b``    | True division  | Quotient of ``a`` and ``b``                            |
| ``a // b``   | Floor division | Quotient of ``a`` and ``b``, removing fractional parts |
| ``a % b``    | Modulus        | Integer remainder after division of ``a`` by ``b``     |
| ``a ** b``   | Exponentiation | ``a`` raised to the power of ``b``                     |
| ``-a``       | Negation       | The negative of ``a``                                  |

<span style="display:none"></span>

In [ ]:
pi = 3.14159
diameter = 3

# Create a variable called 'radius' equal to half the diameter
radius = diameter / 2

# Create a variable called 'area'
area = pi * radius ** 2

print('The area of a circle with diameter {} is: {}'.format(diameter, area))

The area of a circle with diameter 3 is: 7.0685775

#### Question 3

Add code to the following cell to swap variables `a` and `b` (so that `a` refers to the object previously referred to by `b` and vice versa).

In [ ]:
a = [1,2,3]
b = [3,2,1]

In [ ]:
c = a
a = b
b = c
print('List a now is:',a)
print('List b now is:',b)

List a now is: [3, 2, 1]
List b now is: [1, 2, 3]

The following trick to swap two variables in one line:

In [ ]:
a = [1,2,3]
b = [3,2,1]

In [ ]:
# another way is 
a,b = b,a
print('List a now is:',a)
print('List b now is:',b)

List a now is: [3, 2, 1]
List b now is: [1, 2, 3]

#### Question 4

a) Add parentheses to the following expression so that it evaluates to 1.\
`5 - 3 // 2`

In [ ]:
3//2

1

In [ ]:
5-3//2

4

In [ ]:
(5-3)//2

1

b) Add parentheses to the following expression so that it evaluates to 0.\
`8 - 3 * 2 - 1 + 1`

In [ ]:
8 - 3 * 2 - 1 + 1

2

In [ ]:
8-3*2-(1+1)  # (8 - 3) * (2 - (1 + 1)) is one solution. There may be others.

0

#### Question 5

Alice, Bob and Carol have agreed to pool their Halloween candy and split it evenly among themselves. For the sake of their friendship, any candies left over will be smashed. For example, if they collectively bring home 91 candies, they'll take 30 each and smash 1.

Write an arithmetic expression below to calculate how many candies they must smash for a given haul.

In [ ]:
91/3

30.333333333333332

In [ ]:
91%3

1

In [ ]:
# Variables representing the number of candies collected by alice, bob, and carol
alice_candies = 121
bob_candies = 77
carol_candies = 109

In [ ]:
121+77+109

307

In [ ]:
307%3

1

In [ ]:
candies = alice_candies + bob_candies + carol_candies
to_smash = candies % 3

print('Total number of candies = {} \nCandies they must smash = {}'.format(candies,to_smash))

Total number of candies = 307
Candies they must smash = 1

<a name='ch2'></a>
## **2- Functions and Getting Help**

<a name='sec2-1'></a>
### 2-1 Getting Help
https://www.kaggle.com/code/colinmorris/functions-and-getting-help#Getting-Help

You saw the `abs()` function in the previous tutorial, but what if you've forgotten what it does?

In [ ]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.

In [ ]:
help(help)

Help on _Helper in module _sitebuiltins object:

class _Helper(builtins.object)
 |  Define the builtin 'help'.
 |
 |  This is a wrapper around pydoc.help that provides a helpful message
 |  when 'help' is typed at the Python interactive prompt.
 |
 |  Calling help() at the Python prompt starts an interactive help session.
 |  Calling help(thing) prints help for the python object 'thing'.
 |
 |  Methods defined here:
 |
 |  __call__(self, *args, **kwds)
 |      Call self as a function.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [ ]:
help()

Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> modules

Please wait a moment while I gather a list of all available modules...

/usr/local/lib/python3.7/dist-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
WARNING: AstropyDeprecationWarning: The private astropy._erfa module has been made into its own package, pyerfa, which is a dependency of astropy and can be imported directly using "import erfa" [astropy._erfa]
/usr/local/lib/python3.7/dist-packages/datascience/tables.py:17: MatplotlibDeprecationWarning:

The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.

/usr/local/lib/python3.7/dist-packages/datascience/util.py:10: MatplotlibDeprecationWarning:

The 'warn' parameter of use() is deprecated since Matplotlib 3.1 and will be removed in 3.3.  If any parameter follows 'warn', they should be pass as keyword, not positionally.

Downloading http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2 to /root/mlxtend_data/shape_predictor_68_face_landmarks.dat.bz2

/usr/lib/python3.7/pkgutil.py:92: UserWarning:

The DICOM readers are highly experimental, unstable, and only work for Siemens time-series at the moment
Please use with caution.  We would be grateful for your help in improving them

/usr/local/lib/python3.7/dist-packages/nltk/twitter/__init__.py:21: UserWarning:

The twython library has not been installed. Some functionality from the twitter package will not be available.

/usr/local/lib/python3.7/dist-packages/psycopg2/__init__.py:144: UserWarning:

The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.

WARNING:pystan:This submodule contains experimental code, please use with caution

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Cython              colorsys            keras               requests_oauthlib
IPython             community           keras_preprocessing resampy
OpenGL              compileall          keyword             resource
PIL                 concurrent          kiwisolver          rlcompleter
ScreenResolution    configparser        korean_lunar_calendar rmagic
__future__          contextlib          langcodes           rpy2
_abc                contextlib2         lib2to3             rsa
_argon2_cffi_bindings contextvars         libfuturize         runpy
_ast                convertdate         libpasteurize       samples
_asyncio            copy                librosa             sched
_bisect             copyreg             lightgbm            scipy
_blake2             coverage            linecache           scs
_bootlocale         coveralls           llvmlite            seaborn
_bz2                crcmod              lmdb                secrets
_cffi_backend       crypt               locale              select
_codecs             csv                 logging             selectors
_codecs_cn          ctypes              lsb_release         semver
_codecs_hk          cufflinks           lunarcalendar       send2trash
_codecs_iso2022     curses              lxml                setuptools
_codecs_jp          cv2                 lzma                setuptools_git
_codecs_kr          cvxopt              macpath             shapely
_codecs_tw          cvxpy               mailbox             shelve
_collections        cycler              mailcap             shlex
_collections_abc    cymem               markdown            shutil
_compat_pickle      cython              markupsafe          signal
_compression        cythonmagic         marshal             simplegeneric
_contextvars        daft                math                site
_crypt              dask                matplotlib          sitecustomize
_csv                dataclasses         matplotlib_inline   six
_ctypes             datascience         matplotlib_venn     skimage
_ctypes_test        datetime            mimetypes           sklearn
_curses             dateutil            missingno           sklearn_pandas
_curses_panel       dbm                 mistune             slugify
_cvxcore            dbus                mizani              smart_open
_datetime           debugpy             mlxtend             smtpd
_dbm                decimal             mmap                smtplib
_decimal            decorator           modulefinder        sndhdr
_distutils_hack     defusedxml          more_itertools      snowballstemmer
_dummy_thread       descartes           moviepy             socket
_ecos               difflib             mpmath              socketserver
_elementtree        dill                msgpack             socks
_functools          dis                 multiprocess        sockshandler
_hashlib            distributed         multiprocessing     softwareproperties
_heapq              distutils           multitasking        sortedcontainers
_imp                dlib                murmurhash          soundfile
_io                 docopt              music21             soupsieve
_json               docs                natsort             spacy
_locale             doctest             nbclient            spacy_legacy
_lsprof             docutils            nbconvert           spacy_loggers
_lzma               dopamine            nbformat            sphinx
_markupbase         dot_parser          nest_asyncio        spwd
_md5                dummy_threading     netCDF4             sql
_multibytecodec     easydict            netrc               sqlalchemy
_multiprocess       ecos                networkx            sqlite3
_multiprocessing    editdistance        nibabel             sqlparse
_opcode             ee                  nis                 sre_compile
_operator           email               nisext              sre_constants
_osx_support        en_core_web_sm      nltk                sre_parse
_pickle             encodings           nntplib             srsly
_plotly_future_     entrypoints         notebook            ssl
_plotly_utils       enum                ntpath              stat
_posixsubprocess    ephem               nturl2path          statistics
_py_abc             erfa                numba               statsmodels
_pydecimal          errno               numbergen           storemagic
_pyio               et_xmlfile          numbers             string
_pyrsistent_version examples            numexpr             stringprep
_pytest             fa2                 numpy               struct
_queue              fastai              oauth2client        subprocess
_random             fastcore            oauthlib            sunau
_rinterface_cffi_abi fastdownload        ogr                 symbol
_rinterface_cffi_api fastdtw             okgrade             sympy
_scs_direct         fastjsonschema      opcode              sympyprinting
_scs_indirect       fastprogress        openpyxl            symtable
_sha1               fastrlock           operator            sys
_sha256             faulthandler        opt_einsum          sysconfig
_sha3               fbprophet           optparse            syslog
_sha512             fcntl               os                  tables
_signal             feather             osgeo               tabnanny
_sitebuiltins       filecmp             osqp                tabulate
_socket             fileinput           osqppurepy          tarfile
_soundfile          filelock            osr                 tblib
_sqlite3            firebase_admin      ossaudiodev         telnetlib
_sre                fix_yahoo_finance   packaging           tempfile
_ssl                flask               palettable          tenacity
_stat               flatbuffers         pandas              tensorboard
_string             fnmatch             pandas_datareader   tensorboard_data_server
_strptime           folium              pandas_gbq          tensorboard_plugin_wit
_struct             formatter           pandas_profiling    tensorflow
_symtable           fractions           pandocfilters       tensorflow_datasets
_sysconfigdata_m_linux_x86_64-linux-gnu ftplib              panel               tensorflow_estimator
_sysconfigdata_m_x86_64-linux-gnu functools           param               tensorflow_gcs_config
_testbuffer         future              parser              tensorflow_hub
_testcapi           gast                parso               tensorflow_io_gcs_filesystem
_testimportmultiple gc                  past                tensorflow_metadata
_testmultiphase     gdal                pasta               tensorflow_probability
_thread             gdalconst           pathlib             termcolor
_threading_local    gdalnumeric         pathy               terminado
_tkinter            gdown               patsy               termios
_tracemalloc        genericpath         pdb                 test
_warnings           gensim              pep517              testpath
_weakref            geographiclib       pexpect             tests
_weakrefset         geopy               pickle              text_unidecode
_xxtestfuzz         getopt              pickleshare         textblob
abc                 getpass             pickletools         textwrap
absl                gettext             pip                 theano
aifc                gi                  pipes               thinc
alabaster           gin                 piptools            this
albumentations      glob                pkg_resources       threading
altair              glob2               pkgutil             threadpoolctl
antigravity         gnm                 platform            tifffile
apiclient           google_auth_httplib2 plistlib            time
appdirs             google_auth_oauthlib plotly              timeit
apt                 google_drive_downloader plotlywidget        tinycss2
apt_inst            googleapiclient     plotnine            tkinter
apt_pkg             googlesearch        pluggy              tlz
aptsources          graphviz            pooch               token
argon2              greenlet            poplib              tokenize
argparse            gridfs              portpicker          tomli
array               grp                 posix               toolz
arviz               grpc                posixpath           torch
ast                 gspread             pprint              torchaudio
astor               gspread_dataframe   prefetch_generator  torchsummary
astropy             gym                 preshed             torchtext
astunparse          gzip                prettytable         torchvision
asynchat            h5py                profile             tornado
asyncio             hashlib             progressbar         tqdm
asyncore            heapdict            prometheus_client   trace
atari_py            heapq               promise             traceback
atexit              hijri_converter     prompt_toolkit      tracemalloc
atomicwrites        hmac                pstats              traitlets
attr                holidays            psutil              tree
attrs               holoviews           psycopg2            tty
audioop             html                pty                 turtle
audioread           html5lib            ptyprocess          tweepy
autograd            http                pvectorc            typeguard
autoreload          httpimport          pwd                 typer
babel               httplib2            py                  types
backcall            httplib2shim        py_compile          typing
base64              humanize            pyarrow             typing_extensions
bdb                 hyperopt            pyasn1              tzlocal
bin                 ideep4py            pyasn1_modules      unicodedata
binascii            idna                pyclbr              unittest
binhex              imageio             pycocotools         uritemplate
bisect              imagesize           pycparser           urllib
bleach              imaplib             pyct                urllib3
blis                imblearn            pydantic            uu
bokeh               imgaug              pydata_google_auth  uuid
boost               imghdr              pydoc               vega_datasets
branca              imp                 pydoc_data          venv
bs4                 importlib           pydot               vis
bson                importlib_metadata  pydot_ng            warnings
builtins            importlib_resources pydotplus           wasabi
bz2                 imutils             pydrive             wave
cProfile            inflect             pyemd               wcwidth
cachecontrol        iniconfig           pyexpat             weakref
cached_property     inspect             pyglet              webbrowser
cachetools          intervaltree        pygments            webencodings
caffe2              io                  pygtkcompat         werkzeug
calendar            ipaddress           pylab               wheel
catalogue           ipykernel           pymc3               widgetsnbextension
certifi             ipykernel_launcher  pymeeus             wordcloud
cffi                ipython_genutils    pymongo             wrapt
cftime              ipywidgets          pymystem3           wsgiref
cgi                 isympy              pyparsing           xarray
cgitb               itertools           pyrsistent          xarray_einstats
chardet             itsdangerous        pysndfile           xdrlib
charset_normalizer  jax                 pystan              xgboost
chess               jaxlib              pytest              xkit
chunk               jedi                python_utils        xlrd
clang               jieba               pytz                xlwt
click               jinja2              pyviz_comms         xml
client              joblib              pywt                xmlrpc
cloudpickle         jpeg4py             pyximport           xxlimited
cmake               json                qdldl               xxsubtype
cmath               jsonschema          qtconsole           yaml
cmd                 jupyter             qtpy                yellowbrick
cmdstanpy           jupyter_client      queue               zict
code                jupyter_console     quopri              zipapp
codecs              jupyter_core        random              zipfile
codeop              jupyterlab_plotly   re                  zipimport
colab               jupyterlab_pygments readline            zipp
collections         jupyterlab_widgets  regex               zlib
colorcet            kaggle              reprlib             zmq
colorlover          kapre               requests

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose name or summary contain the string "spam".

help> quite
No Python documentation found for 'quite'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

help> quit

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.

In [ ]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.

In [ ]:
help(round(-2.01))

Help on int object:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |
 |  Methods defined here:
 |
 |  __abs__(self, /)
 |      abs(self)
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __and__(self, value, /)
 |      Return self&value.
 |
 |  __bool__(self, /)
 |      self != 0
 |
 |  __ceil__(...)
 |      Ceiling of an Integral returns itself.
 |
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __float__(self, /)
 |      float(self)
 |
 |  __floor__(...)
 |      Flooring an Integral returns itself.
 |
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |
 |  __format__(self, format_spec, /)
 |      Default object formatter.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __index__(self, /)
 |      Return self converted to an integer, if self is suitable for use as an index into a list.
 |
 |  __int__(self, /)
 |      int(self)
 |
 |  __invert__(self, /)
 |      ~self
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __lshift__(self, value, /)
 |      Return self<<value.
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mod__(self, value, /)
 |      Return self%value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __neg__(self, /)
 |      -self
 |
 |  __or__(self, value, /)
 |      Return self|value.
 |
 |  __pos__(self, /)
 |      +self
 |
 |  __pow__(self, value, mod=None, /)
 |      Return pow(self, value, mod).
 |
 |  __radd__(self, value, /)
 |      Return value+self.
 |
 |  __rand__(self, value, /)
 |      Return value&self.
 |
 |  __rdivmod__(self, value, /)
 |      Return divmod(value, self).
 |
 |  __repr__(self, /)
 |      Return repr(self).
 |
 |  __rfloordiv__(self, value, /)
 |      Return value//self.
 |
 |  __rlshift__(self, value, /)
 |      Return value<<self.
 |
 |  __rmod__(self, value, /)
 |      Return value%self.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __ror__(self, value, /)
 |      Return value|self.
 |
 |  __round__(...)
 |      Rounding an Integral returns itself.
 |      Rounding with an ndigits argument also returns an integer.
 |
 |  __rpow__(self, value, mod=None, /)
 |      Return pow(value, self, mod).
 |
 |  __rrshift__(self, value, /)
 |      Return value>>self.
 |
 |  __rshift__(self, value, /)
 |      Return self>>value.
 |
 |  __rsub__(self, value, /)
 |      Return value-self.
 |
 |  __rtruediv__(self, value, /)
 |      Return value/self.
 |
 |  __rxor__(self, value, /)
 |      Return value^self.
 |
 |  __sizeof__(self, /)
 |      Returns size in memory, in bytes.
 |
 |  __str__(self, /)
 |      Return str(self).
 |
 |  __sub__(self, value, /)
 |      Return self-value.
 |
 |  __truediv__(self, value, /)
 |      Return self/value.
 |
 |  __trunc__(...)
 |      Truncating an Integral returns itself.
 |
 |  __xor__(self, value, /)
 |      Return self^value.
 |
 |  bit_length(self, /)
 |      Number of bits necessary to represent self in binary.
 |
 |      >>> bin(37)
 |      '0b100101'
 |      >>> (37).bit_length()
 |      6
 |
 |  conjugate(...)
 |      Returns self, the complex conjugate of any int.
 |
 |  to_bytes(self, /, length, byteorder, *, signed=False)
 |      Return an array of bytes representing an integer.
 |
 |      length
 |        Length of bytes object to use.  An OverflowError is raised if the
 |        integer is not representable with the given number of bytes.
 |      byteorder
 |        The byte order used to represent the integer.  If byteorder is 'big',
 |        the most significant byte is at the beginning of the byte array.  If
 |        byteorder is 'little', the most significant byte is at the end of the
 |        byte array.  To request the native byte order of the host system, use
 |        `sys.byteorder' as the byte order value.
 |      signed
 |        Determines whether two's complement is used to represent the integer.
 |        If signed is False and a negative integer is given, an OverflowError
 |        is raised.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  from_bytes(bytes, byteorder, *, signed=False) from builtins.type
 |      Return the integer represented by the given array of bytes.
 |
 |      bytes
 |        Holds the array of bytes to convert.  The argument must either
 |        support the buffer protocol or be an iterable object producing bytes.
 |        Bytes and bytearray are examples of built-in objects that support the
 |        buffer protocol.
 |      byteorder
 |        The byte order used to represent the integer.  If byteorder is 'big',
 |        the most significant byte is at the beginning of the byte array.  If
 |        byteorder is 'little', the most significant byte is at the end of the
 |        byte array.  To request the native byte order of the host system, use
 |        `sys.byteorder' as the byte order value.
 |      signed
 |        Indicates whether two's complement is used to represent the integer.
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  denominator
 |      the denominator of a rational number in lowest terms
 |
 |  imag
 |      the imaginary part of a complex number
 |
 |  numerator
 |      the numerator of a rational number in lowest terms
 |
 |  real
 |      the real part of a complex number

In [ ]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

<a name='sec2-2'></a>
### 2-2 Defining functions
https://www.kaggle.com/code/colinmorris/functions-and-getting-help#Defining-functions

In [ ]:
def least_difference(a,b,c):
  diff1 = abs(a - b)
  diff2 = abs(b - c)
  diff3 = abs(a - c)
  
  return min(diff1, diff2, diff3)

In [ ]:
least_difference(1,10,100)

9

In [ ]:
help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)

> Python isn't smart enough to read my code and turn it into a nice English description. However, when I write a function, I can provide a description in what's called the **docstring**.

#### Docstrings
https://www.kaggle.com/code/colinmorris/functions-and-getting-help#Docstrings

Good programmers use docstrings unless they expect to throw away the code soon after it's used (which is rare). So, you should start writing docstrings, too!

In [ ]:
def least_difference(a,b,c):
  """Return the smallest difference between any two numbers
  among a, b and c.
  
  >>> least_difference(1, 5, -5)
  4
  """

  diff1 = abs(a - b)
  diff2 = abs(b - c)
  diff3 = abs(a - c)
  
  return min(diff1, diff2, diff3)

**Example call**\
an example function **call and result**. (The **>>>** is a reference to the command prompt used in Python interactive shells.)



```
>>> least_difference(1,5,-5)
4
```

In [ ]:
help(least_difference)

Help on function least_difference in module __main__:

least_difference(a, b, c)
    Return the smallest difference between any two numbers
    among a, b and c.

    >>> least_difference(1, 5, -5)
    4

<a name='sec2-3'></a>
### 2-3 Functions that don't return
https://www.kaggle.com/code/colinmorris/functions-and-getting-help#Functions-that-don't-return

In [ ]:
def least_difference(a,b,c):
  """Return the smallest difference between any two numbers
  among a, b and c.
  
  >>> least_difference(1, 5, -5)
  4
  """

  diff1 = abs(a - b)
  diff2 = abs(b - c)
  diff3 = abs(a - c)
  
  min(diff1, diff2, diff3)

print(
    least_difference(1,10,100),
    least_difference(1,10,10),
    least_difference(5,6,7)
)

None None None

In [ ]:
mystery1 = print()
mystery2 = help()

print(mystery1, mystery2)

Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> quit

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.
None None

In [ ]:
print(mystery1)

None

<a name='sec2-4'></a>
### 2-4 Default argument
https://www.kaggle.com/code/colinmorris/functions-and-getting-help#Default-arguments

In [ ]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.

In [ ]:
print(1,2,3, sep='<')

1<2<3

In [ ]:
print(1,2,3)

1 2 3

In [ ]:
def greet(who = 'Colin'):
  print('Hello,', who)

In [ ]:
greet()

Hello, Colin

In [ ]:
greet(who = 'Jameel')

Hello, Jameel

In [ ]:
greet('KAGGLE')

Hello, KAGGLE

<a name='sec2-5'></a>
### 2-5 Functions Applied to Functions
https://www.kaggle.com/code/colinmorris/functions-and-getting-help#Functions-Applied-to-Functions

In [ ]:
def mult_by_five(x):
  return 5 * x

In [ ]:
mult_by_five(10)

50

Supplying functions as arguments to other functions **"higher-order functions"**

In [ ]:
def call(fn, arg):
  """
  Call fn on arg
  """
  return fn(arg)

In [ ]:
call(mult_by_five,10)

50

In [ ]:
def squared_call(fn, arg):
  """
  Call fn on the result of calling fn on arg
  """
  return fn(fn(arg))

In [ ]:
squared_call(mult_by_five,1)

25

In [ ]:
squared_call(mult_by_five,10)

250

In [ ]:
print(
    call(mult_by_five,1),
    squared_call(mult_by_five,1),
    sep='\n'
)

5
25

**higher-order functions** built into Python

In [ ]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.

In [ ]:
max(100,51,14)

100

In [ ]:
def mod_5(x):
  """
  Return the remainder of x after dividing by 5
  """
  return x % 5

In [ ]:
mod_5(100)

0

In [ ]:
mod_5(14)

4

In [ ]:
print(
    'Which number is biggest?',
    max(100,51,14),
    'Which number is the biggest modulo 5 ?',
    max(100,51,14,key = mod_5),
    sep='\n'
)

Which number is biggest?
100
Which number is the biggest modulo 5 ?
14

<a name='ex2'></a>
### Exercise: Functions and Getting Help

#### Question 1

Return the given number rounded to two decimal places

In [ ]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.

    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.

In [ ]:
def round_to_two_places(num):
    """Return the given number rounded to two decimal places. 
    
    >>> round_to_two_places(3.14159)
    3.14
    """
    return round(num,2)

In [ ]:
round_to_two_places(3.14159)

3.14

#### Question 2

round(number, ndigits=None)\
put the `ndigits` negitive

In [ ]:
round(3.14159,-2)

0.0

In [ ]:
round(338424,-1) # rounds to the nearest 10

338420

In [ ]:
round(338424,-2) # rounds to the nearest 100

338400

In [ ]:
area = 2166086
print('The area of Greenland is {} km²'.format(format(round(area,-3),',')))

The area of Greenland is 2,166,000 km²

>(We'll talk about how we would get the commas later when we talk about string formatting :)) 
https://stackoverflow.com/questions/20686629/how-to-convert-an-integer-to-a-comma-separated-string

#### Question 3

In [ ]:
def to_smash(total_candies):
    """Return the number of leftover candies that must be smashed after distributing
    the given number of candies evenly between 3 friends.
    
    >>> to_smash(91)
    1
    """
    return total_candies % 3

In [ ]:
to_smash(91)

1

Modify the function `to_smach()` so that it optionally **takes a second argument representing the number of friends** the candies are being split between. If no second argument is provided, it should assume 3 friends, as before.

In [ ]:
def to_smash(total_candies,friends=3):
    """Return the number of leftover candies that must be smashed after distributing
    the given number of candies evenly between the friends.
    
    >>> to_smash(91)
    1
    """
    return total_candies % friends

In [ ]:
to_smash(91)

1

In [ ]:
to_smash(100,4)

0

In [ ]:
to_smash(101,4)

1

#### Question 4

Each code cell below contains some commented buggy code.

a) 

```
ruound_to_two_places(9.9999)
```

In [ ]:
# ruound_to_two_places(9.9999)
ruound_to_two_places(9.9999)

NameError: ignored

In [ ]:
round_to_two_places(9.9999)

10.0

b) 

```
x = -10
y = 5
# Which of the two variables above has the smallest absolute value?
smallest_abs = min(abs(x, y))
```

In [ ]:
# x = -10
# y = 5
# # Which of the two variables above has the smallest absolute value?
# smallest_abs = min(abs(x, y))

x = -10
y = 5
# Which of the two variables above has the smallest absolute value?
smallest_abs = min(abs(x, y))

TypeError: ignored

In [ ]:
abs(-10)

10

In [ ]:
min(abs(-10),abs(5))

5

In [ ]:
x = -10
y = 5
# Which of the two variables above has the smallest absolute value?
smallest_abs = min(abs(x), abs(y))

In [ ]:
smallest_abs

5

c)

```
def f(x):
    y = abs(x)
return y

print(f(5))
```

In [ ]:
# def f(x):
#     y = abs(x)
# return y

# print(f(5))


def f(x):
    y = abs(x)
return y

print(f(5))

SyntaxError: ignored

In [ ]:
def f(x):
    y = abs(x)
    return y

print(f(5))

5

<a name='ch3'></a>
## **3- Booleans and Conditionals**

<a name='sec3-1'></a>
### 3-1 Booleans
https://www.kaggle.com/code/colinmorris/booleans-and-conditionals#Booleans

In [ ]:
x = True
print(x)
print(type(x))

True
<class 'bool'>

#### Comparison Operations

In [ ]:
def can_run_for_president(age):
    """Can someone of the given age run for president in the US?"""
    # The US Constitution says you must be at least 35 years old
    return age >= 35

In [ ]:
print("Can a 19-year-old run for president?", can_run_for_president(19))
print("Can a 45-year-old run for president?", can_run_for_president(45))

Can a 19-year-old run for president? False
Can a 45-year-old run for president? True

In [ ]:
3.0 == 3

True

In [ ]:
"3" == 3.0

False

In [ ]:
# check if a number is odd by checking that the modulus
def is_odd(n):
  return (n % 2) != 0

In [ ]:
print("Is 100 odd?", is_odd(100))
print("Is -1 odd?", is_odd(-1))

Is 100 odd? False
Is -1 odd? True

#### Combining Boolean Values

In [ ]:
def can_run_for_president(age, is_natural_born_citizen):
    """Can someone of the given age and citizenship status run
     for president in the US?"""
    # The US Constitution says you must be a natural born citizen 
    # *and* at least 35 years old
    return is_natural_born_citizen and (age >= 35)

In [ ]:
print(can_run_for_president(19, True))
print(can_run_for_president(55, False))
print(can_run_for_president(55, True))

False
False
True

In [ ]:
True or True

True

In [ ]:
True and False

False

In [ ]:
True or False

True

In [ ]:
True or True and False

True

> `and` is evaluated before `or`\
*but a safer bet is to just use liberal **parentheses**.*

<a name='sec3-2'></a>
### 3-2 Conditionals
https://www.kaggle.com/code/colinmorris/booleans-and-conditionals#Conditionals

#### Conditional statements (if-then statements)

In [ ]:
def inspect(x):
    if x == 0:
        print(x, "is zero")
    elif x > 0:
        print(x, "is positive")
    elif x < 0:
        print(x, "is negative")
    else:
        print(x, "is unlike anything I've ever seen...")

In [ ]:
inspect(0)

0 is zero

In [ ]:
inspect(20)

20 is positive

In [ ]:
inspect(-100000)

-100000 is negative

In [ ]:
inspect(5.5)

5.5 is positive

In [ ]:
def f(x):
    if x > 0:
        print("Only printed when x is positive; x =", x)
        print("Also only printed when x is positive; x =", x)
    print("Always printed, regardless of x's value; x =", x)

In [ ]:
f(1)

Only printed when x is positive; x = 1
Also only printed when x is positive; x = 1
Always printed, regardless of x's value; x = 1

In [ ]:
f(0)

Always printed, regardless of x's value; x = 0

#### Boolean conversion

In [ ]:
int('555')

555

In [ ]:
float(5)

5.0

Python has a `bool()` function which turns things into bools.

In [ ]:
bool(1)

True

In [ ]:
bool(0)

False

>all numbers are treated as true, except 0

In [ ]:
bool('jameel')

True

In [ ]:
bool('')

False

In [ ]:
bool(' ')

True

> all strings are treated as true, except the empty string ""

In [ ]:
bool(list())

False

In [ ]:
bool(tuple())

False

In [ ]:
bool(str())

False

> Generally **empty sequences** (strings, lists, and other types we've yet to see like lists and tuples) are "falsey" and the rest are "truthy"

In [ ]:
if 0:
    print(0)
elif "spam":
    print("spam")

spam

<a name='ex3'></a>
### Exercise: Booleans and Conditionals

#### Question 1

In [ ]:
def sign(num):
    """
    the function takes a numerical argument and returns 
    -1 if it's negative, 
    1 if it's positive, and 
    0 if it's 0.
    """
    if num > 0:
      return 1
    
    elif num < 0:
      return -1

    elif num == 0:
      return 0

In [ ]:
sign(0)

0

In [ ]:
sign(-669)

-1

In [ ]:
sign(100)

1

#### Question 2

In [ ]:
def to_smash(total_candies):
    """Return the number of leftover candies that must be smashed 
    after distributing the given number of candies evenly between 3 friends.
    
    >>> to_smash(91)
    1
    """
    print("Splitting", total_candies, "candies")
    return total_candies % 3

to_smash(91)

Splitting 91 candies

1

What happens if we call it with total_candies = 1?

In [ ]:
to_smash(1)

Splitting 1 candies

1

> (If there's only one candy, we should use the singular "candy" instead of the plural "candies")

In [ ]:
def to_smash(total_candies):
    """Return the number of leftover candies that must be smashed after distributing
    the given number of candies evenly between 3 friends.
    
    >>> to_smash(91)
    1
    """
    if total_candies == 1:
        print("Splitting", total_candies, "candy")

    else:
        print("Splitting", total_candies, "candies")
        
    return total_candies % 3

In [ ]:
to_smash(91)

Splitting 91 candies

1

In [ ]:
to_smash(1)

Splitting 1 candy

1

Here's a slightly more succinct solution using a conditional expression:

In [ ]:
def to_smash(total_candies):
    """Return the number of leftover candies that must be smashed after distributing
    the given number of candies evenly between 3 friends.
    
    >>> to_smash(91)
    1
    """
    print("Splitting", total_candies, "candy" if total_candies == 1 else "candies")
        
    return total_candies % 3

In [ ]:
to_smash(1)

Splitting 1 candy

1

In [ ]:
to_smash(91)

Splitting 91 candies

1

#### Question 3

The function below uses our first attempt at turning this logic into a Python expression. I claimed that there was a bug in that code. Can you find it?

I'm safe from today's weather....

- if I have an umbrella...
- or if the rain isn't too heavy and I have a hood...
- otherwise, I'm still fine unless it's raining and it's a workday

In [ ]:
def prepared_for_weather(have_umbrella, rain_level, have_hood, is_workday):
    # Don't change this code. Our goal is just to find the bug, not fix it!
    return have_umbrella or rain_level < 5 and have_hood or not rain_level > 0 and is_workday

In [ ]:
# Change the values of these inputs so they represent a case where prepared_for_weather
# returns the wrong answer.
have_umbrella = True
rain_level = 0.0
have_hood = True
is_workday = True

In [ ]:
# Check what the function returns given the current values of the variables above
actual = prepared_for_weather(have_umbrella, rain_level, have_hood, is_workday)
print(actual)

True

In [ ]:
True or True

True

In [ ]:
True or False

True

In [ ]:
True and False

False

In [ ]:
True or True and False

True

In [ ]:
True or (True and False)

True

> True or (True and False)\
True or False\
True

In [ ]:
True or True and True or not False and True

True

In [ ]:
True or (True and True) or not (False and True)

True

In [ ]:
def prepared_for_weather(have_umbrella, rain_level, have_hood, is_workday):
    # Don't change this code. Our goal is just to find the bug, not fix it!
    return have_umbrella or rain_level < 5 and have_hood or not rain_level > 0 and is_workday

In [ ]:
have_umbrella = True
rain_level = 0.0
have_hood = True
is_workday = True

# Check what the function returns given the current values of the variables above
actual = prepared_for_weather(have_umbrella, rain_level, have_hood, is_workday)
print(actual)

True

In [ ]:
have_umbrella = False
rain_level = 0.0
have_hood = False
is_workday = False

actual = prepared_for_weather(have_umbrella, rain_level, have_hood, is_workday)
print(actual)

False

#### Question 4

In [ ]:
def is_negative(number):
    if number < 0:
        return True
    else:
        return False

See if you can come up with an equivalent body that uses just one line of code

In [ ]:
def concise_is_negative(number):
    return number < 0

In [ ]:
concise_is_negative(5)

False

In [ ]:
concise_is_negative(-5)

True

#### Question 5

a)

In [ ]:
def onionless(ketchup, mustard, onion):
    """Return whether the customer doesn't want onions.
    """
    return not onion

In [ ]:
def wants_all_toppings(ketchup, mustard, onion):
    """Return whether the customer wants "the works" (all 3 toppings)
    """
    return ketchup and mustard and onion

b)

In [ ]:
def wants_plain_hotdog(ketchup, mustard, onion):
    """Return whether the customer wants a plain hot dog with no toppings.
    """
    return not ketchup and not mustard and not onion

One solution looks like:\
We can also "factor out" the nots to get:

In [ ]:
def wants_plain_hotdog(ketchup, mustard, onion):
    """Return whether the customer wants a plain hot dog with no toppings.
    """
    return not (ketchup or mustard or onion)

c)

In [ ]:
def exactly_one_sauce(ketchup, mustard, onion):
    """Return whether the customer wants either ketchup or mustard, but not both.
    (You may be familiar with this operation under the name "exclusive or")
    """
    return ketchup or mustard or onion

In [ ]:
exactly_one_sauce(True,False, False)

False

In [ ]:
exactly_one_sauce(True,True, True)

True

In [ ]:
True and False

False

In [ ]:
True and not True

False

In [ ]:
def exactly_one_sauce(ketchup, mustard, onion):
    """Return whether the customer wants either ketchup or mustard, but not both.
    (You may be familiar with this operation under the name "exclusive or")
    """
    return (mustard and not ketchup) or (ketchup and not mustard)

In [ ]:
exactly_one_sauce(True,True,True)

False

In [ ]:
exactly_one_sauce(True,False,True)

True

In [ ]:
exactly_one_sauce(False,True,True)

True

#### Question 6

We’ve seen that calling `bool()` on an integer returns `False` if it’s equal to 0 and `True` otherwise.

In [1]:
bool(951)

True

In [2]:
bool(0)

False

 What happens if we call `int()` on a bool?

In [3]:
int(True)

1

In [4]:
int(False)

0

Can you take advantage of this to write a succinct function that corresponds to the English sentence "does the customer want exactly one topping?"?

In [9]:
def exactly_one_topping(ketchup, mustard, onion):
    """Return whether the customer wants exactly one of the three available toppings
    on their hot dog.
    """
    return int(ketchup and not mustard and not onion) or int(not ketchup and mustard and not onion) or int(not ketchup and not mustard and onion)

In [10]:
exactly_one_topping(True,False,False)

1

In [11]:
exactly_one_topping(True,True,True)

0

This condition would be pretty complicated to express using just and, or and not, but using boolean-to-integer conversion gives us this short solution:

In [12]:
def exactly_one_topping(ketchup, mustard, onion):
    """Return whether the customer wants exactly one of the three available toppings
    on their hot dog.
    """
    return (int(ketchup) + int(mustard) + int(onion)) == 1

In [13]:
exactly_one_topping(True,True,True)

False

In [14]:
exactly_one_topping(True,False,False)

True

Fun fact: we don't technically need to call int on the arguments. Just by doing addition with booleans, Python implicitly does the integer conversion. So we could also write...

In [15]:
def exactly_one_topping(ketchup, mustard, onion):
    """Return whether the customer wants exactly one of the three available toppings
    on their hot dog.
    """
    return (ketchup + mustard + onion) == 1

In [16]:
print(exactly_one_topping(True,True,True))
print(exactly_one_topping(True,False,False))

False
True

#### Question 7

<a name='ch4'></a>
## **4- Lists**

<a name='ch5'></a>
## **5- Loops and List Comprehensions**

<a name='ch6'></a>
## **6- Strings and Dictionaries**

<a name='ch7'></a>
## **7- Working with External Libraries**

<a name='bonus'></a>
## **Bonus Exercise : Titanic Tutorial**

Make your first submission to a Kaggle competition!

\
The [notebook](https://www.kaggle.com/code/alexisbcook/titanic-tutorial/notebook) is beginner-friendly and does not assume you have any experience with coding. At the same time, you'll learn how to author your own notebooks on Kaggle, and it gives you a great idea of what you'll be able to do if you continue to learn data science!

\
If you're interested in learning more, we strongly suggest our (3-hour) [Intro to Machine Learning course](https://www.kaggle.com/learn/intro-to-machine-learning), which will help you fully understand all of the code that we've presented here. You'll also know enough to generate even better predictions!

In this section,**you'll train your own machine learning model to improve your predictions**. If you've never written code before or don't have any experience with machine learning, don't worry! We don't assume any prior experience in this tutorial.

### Load the data

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/content/drive/MyDrive/iMLND/Titanic'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/content/drive/MyDrive/iMLND/Titanic/titanic.zip
/content/drive/MyDrive/iMLND/Titanic/gender_submission.csv
/content/drive/MyDrive/iMLND/Titanic/train.csv
/content/drive/MyDrive/iMLND/Titanic/test.csv

In [ ]:
train_data = pd.read_csv('/content/drive/MyDrive/iMLND/Titanic/train.csv')
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
test_data = pd.read_csv('/content/drive/MyDrive/iMLND/Titanic/test.csv')
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

- Find **patterns** in train.csv that help us **predict** whether the passengers in test.csv survived

### Explore a pattern

The sample submission file in **gender_submission.csv** assumes that all female passengers survived (and all male passengers died).

Is this a reasonable first guess? We'll check if this pattern holds true in the data (in **train.csv**).

In [ ]:
women = train_data.loc[train_data.Sex == 'female']['Survived']
rate_women = sum(women)/len(women)

print("% of women who survived:", rate_women)

% of women who survived: 0.7420382165605095

In [ ]:
men = train_data.loc[train_data.Sex == 'male']['Survived']
rate_men = sum(men)/len(men)

print("% of men who survived:", rate_men)

% of men who survived: 0.18890814558058924

> From this you can see that almost 75% of the women on board survived, whereas only 19% of the men lived to tell about it. Since gender seems to be such a strong indicator of survival, the submission file in **gender_submission.csv** is not a bad first guess!

This gender-based submission bases its predictions **on only a single column**. As you can imagine, by **considering multiple columns**, we can discover more **complex patterns** that can potentially yield better-informed predictions.*Since it is quite difficult to consider several columns at once (or, it would take a long time to consider all possible patterns in many different columns simultaneously), we'll use **machine learning to automate this** for us.*

### Machine learning model

- Build a **random forest model**
 *the random forest model makes a democratic decision: the outcome with the **most votes wins**!*

The code cell below looks for patterns in four different columns ("**Pclass**", "**Sex**", "**SibSp**", and "**Parch**") of the data. It constructs the trees in the random forest model based on patterns in the **train.csv** file, before generating predictions for the passengers in **test.csv**. The code also saves these new predictions in a CSV file **submission.csv**.

In [ ]:
from sklearn.ensemble import RandomForestClassifier

y = train_data['Survived']

features = ["Pclass","Sex","SibSp","Parch"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X,y)
predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId':test_data.PassengerId,
                       'Survived': predictions})

output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!